/**
 * Preview Framework — STORE_API_GATEWAY_ARCHITECTURE.md §4.2's already-
 * designed "signed preview token generated by the CMS admin surface,
 * short-lived, single-page-scoped, never a general bypass" — implemented
 * for real here, ahead of any CMS/Theme/Landing surface existing to call
 * it, per this slice's own explicit scope.
 */

export type PreviewKind = 'cms' | 'theme' | 'landing' | 'draft';

export interface PreviewContext {
  kind: PreviewKind;
  /** The entity being previewed — a Page id, a Theme id, a Landing page id. Opaque to this framework; interpreted by whichever future route consumes it. */
  targetId: string;
  /** Never a general "see everything in draft" bypass — one context previews one target. */
  issuedAt: number;
  expiresAt: number;
}

export interface MintedPreview {
  token: string;
  url: string;
  context: PreviewContext;
}
